The Fibonacci sequence is the series of numbers 0, 1, 1, 2, 3, 5, 8, .... Formally, it can be expressed as:
f ib0 = 0
f ib1 = 1
f ibn = f ibn−1 + f ibn−2
Write a multithreaded program that generates the Fibonacci sequence. This program should work as follows: On the command line, the user will enter the number of Fibonacci numbers that the program is to generate. The program will then create a separate thread that will generate the Fibonacci numbers, placing the sequence in data that can be shared by the threads (an array is probably the most convenient data structure). When the thread finishes execution, the parent thread will output the sequence generated by the child thread. Because the
parent thread cannot begin outputting the Fibonacci sequence until the child thread finishes, the parent thread will have to wait for the child thread to finish.

#include<stdio.h>
#include<pthread.h>
#include<unistd.h>
int fib(int a);
void *func(void *a);
int main(){
int a;
pthread_t pthread;
scanf("%d",&a);
pthread_create(&pthread ,NULL,func,(void *)a);
pthread_join(pthread,NULL);
return 0;
}
void *func(void *a){
 int d = (int)a;
 int i;
 for(i=1;i<d;i++){
   printf("%d",fib(i));
 }
}
 int fib(int a){
 if( a<=1){
     //printf("%d \t",(int)a);
     return a;
 }
else{
 return fib(a-1) + fib(a-2); 
 }
 }


